CREATE OR REPLACE TRIGGER trg_time_restrict
BEFORE INSERT OR UPDATE OR DELETE ON EMPLOYEE
BEGIN
    IF TO_CHAR(SYSDATE, 'HH24') >= 19 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Modifications not allowed after 7 PM');
    END IF;
END;
/
