-- 1. Create Tables
CREATE TABLE BOOKS_COPY (
    BOOK_NO NUMBER(5) PRIMARY KEY,
    TITLE VARCHAR2(30),
    COST NUMBER(10)
);

CREATE TABLE EMPLOYEE (
    Eno NUMBER(10) PRIMARY KEY,
    Name VARCHAR2(20),
    Department VARCHAR2(20),
    Salary NUMBER(10)
);

-- 2. Insert Data into BOOKS_COPY
INSERT INTO BOOKS_COPY VALUES (1, 'Book A', 410);
INSERT INTO BOOKS_COPY VALUES (2, 'Book B', 300);
INSERT INTO BOOKS_COPY VALUES (3, 'Book C', 500);
INSERT INTO BOOKS_COPY VALUES (4, 'Book D', 460);

-- 3. Insert Data into EMPLOYEE
INSERT INTO EMPLOYEE VALUES (1, 'Arnab Das', 'IT', 50000);
INSERT INTO EMPLOYEE VALUES (2, 'Suman Guha', 'HR', 45000);
INSERT INTO EMPLOYEE VALUES (3, 'Nisha Mukherjee', 'Finance', 60000);

COMMIT;